"""phase2

Revision ID: 66a9ff73382b
Revises: 97d4491ab1d9
Create Date: 2026-04-22 00:03:25.119055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a9ff73382b'
down_revision: Union[str, None] = '97d4491ab1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_env', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name')
    )
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('api_key_env', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('best_for', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_input_per_m', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cost_output_per_m', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ioc_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('source_ioc', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('related_ioc', sa.String(length=500), nullable=False),
    sa.Column('related_type', sa.String(length=20), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('source_api', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitre_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('technique_name', sa.String(length=200), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('mitigations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitre_mappings')
    op.drop_table('ioc_relationships')
    op.drop_table('llm_configs')
    op.drop_table('api_configs')
    # ### end Alembic commands ###
