"""init

Revision ID: 97d4491ab1d9
Revises: 
Create Date: 2026-04-21 23:53:59.021989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97d4491ab1d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ioc_value', sa.String(length=500), nullable=False),
    sa.Column('ioc_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('severity_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('agents_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_api_calls', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('execution_time_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('api_calls_made', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tool_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_result_id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_result_id'], ['agent_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_tool_results')
    op.drop_table('agent_results')
    op.drop_table('investigations')
    # ### end Alembic commands ###
